### ISSUE TITLE
“chrono-Compatible Low-Level Date Algorithms” and other papers?

### ISSUE THREAD

**Issue by socantre** [HowardHinnant/papers#10]
I noticed today that your home.roadrunner.com/~hhinnant site where you had several useful resources posted is not currently active. It would be nice to have those resources hosted here or at another stable location.

**Comment by HowardHinnant** [comment]
I'm looking for a new home.  And github might be it.  Thanks for the suggestion.

**Comment by socantre** [comment]
You can even host actual websites: https://pages.github.com. So you could just directly copy the content from your old site into a repo and then you get a site: http://HowardHinnant.github.io, or create a site for this repo and get http://HowardHinnant.github.io/papers

**Comment by HowardHinnant** [comment]
I can't thank you enough for your helpful nudge in this direction.  This is exactly what I was looking for, and didn't know it was here.

http://howardhinnant.github.io

**Comment by socantre** [comment]
Well thanks for posting your papers, including the one I subtly hinted I was looking for.

I just read the dining philosophers one and now I'm wondering how the slope of the smart & polite algorithm after cores run out compares with the slope of a theoretical minimum that takes into account limited cores. Also I'm wondering who developed the smart algorithm; I see the Wikipedia page doesn't cover it.

Anyway, thanks again.

P.S. the links in the 'Informal Writing' section of your résumé are broken.

**Comment by HowardHinnant** [comment]
I first coded these algorithms around 1999.  The smart algorithm was derived from "Programming with POSIX Threads by Butenhof, which describes it with two sentences and the title "Try and back off."  I added the calls to yield on a hunch that it might pay off.
