### ISSUE TITLE
insert vs emplace doesn't test emplace constructor

### ISSUE THREAD

**Issue by Erroneous1** [HowardHinnant/papers#11]
One of the main advantages for using emplace would be that you can construct an element in place as demonstrated in Introduction. When I run `v.emplace(v.begin(), 0, nullptr);` on libstdc++ I get 1 fewer destructor and move constructor than `v.insert(v.begin(), X{0, nullptr});` which imo would be a main use case for emplace vs insert. The actual results I got were {1,1,0,0,1,3} vs {1,2,0,0,2,3} for no reallocation and {1,3,0,0,3,0} vs {1,4,0,0,4,0} with reallocation.

**Comment by HowardHinnant** [comment]
I'm afraid you've completely missed the point of the paper.

**Comment by Erroneous1** [comment]
I see I did. It is about comparing insert and emplace where either would work and not insert vs emplace in general. My apologies especially since it is even in stated in its own section in the introduction.
